### ISSUE TITLE
Could you put numbers on the README, i don't want to count blocks

### ISSUE THREAD

**Issue by avoidwork** [eno-lang/benchmarks#1]
I'm curious, but this is a friction point.

**Comment by simonrepp** [comment]
The numbers (in seconds) are given at the end of each bar (right before the library name), are you asking me to remove the graphical bar representations, or am i misreading your request entirely? :) Thanks for the interest!

**Comment by simonrepp** [comment]
I split the report into a "just the numbers" section and a lo-fi graphically implemented representation, hope things are more clear now; thanks for the feedback!

**Comment by avoidwork** [comment]
thanks! i guess i was asking for a separation of the bars & timing, as it was getting missed during scrolling.
